apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommercedemo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ecommercedemo
  source:
    repoURL: https://github.com/AndreiTelteu/Ecommerce-Demo-k8s.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommercedemo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
