apiVersion: apps/v1
kind: Deployment
metadata:
  name:  astro-solidjs
  namespace: ecommercedemo
  labels:
    app: astro-solidjs
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: astro-solidjs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: astro-solidjs
    spec:
      containers:
      - name: astro-solidjs
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 80Mi
          limits:
            cpu: 600m
            memory: 400Mi
      restartPolicy: Always
